version: 2

sources:
  - name: commerce  # Must match what's in your models
    schema: public  # The PostgreSQL schema name
    tables:
      - name: raw_subscriptions
        description: "Raw subscription data from Kafka"
        columns:
          - name: user_id
          - name: plan_id
          - name: is_trial
          - name: timestamp

      - name: raw_login_attempts
        description: "User login attempts data"
        columns:
          - name: user_id
          - name: device_id
          - name: ip_address
          - name: location
          - name: is_successful
          - name: timestamp

      - name: raw_payments
        description: "Payment transaction events"
        columns:
          - name: user_id
          - name: amount
          - name: currency
          - name: status
          - name: timestamp

models:
  - name: stg_user_subscriptions
    description: "Cleaned subscription data"
    columns:
      - name: user_id
        description: "Unique user identifier"
      - name: plan_id
      - name: is_trial
      - name: timestamp

  - name: stg_login_attempts
    description: "Cleaned login attempt data"
    columns:
      - name: user_id
        tests:
          - not_null                   # Ensures no NULL values
          #- unique  
      - name: device_id
      - name: ip_address
      - name: is_successful
        tests:
          - accepted_values:
              values: [true, false]
      - name: timestamp

  - name: stg_payment_events
    description: "Cleaned payment events"
    columns:
      - name: user_id
      - name: amount
        tests:
            - not_null
      - name: status
      - name: timestamp