subscription_misuse:
  outputs:
    dev:
      dbname: streaming
      host: localhost
      password: postgres
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev
